apiVersion: v1
kind: Service
metadata:
  labels:
    app: badger
  name: badger
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: badger
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
