apiVersion: v1
kind: Service
metadata:
  labels:
    app: imagelayers-web
  name: imagelayers-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
    name: http
  selector:
    app: imagelayers-web
  sessionAffinity: None
  type: ClusterIP
